collada.types.Collada(
    library_animations=[],
    library_controllers=[],
    library_effects=[
        collada.types.LibraryEffects(
            id=None,
            name=None,
            effects=[
                collada.types.Effect(
                    id='CubeMaterialTextured',
                    name=None,
                    profile_common=[
                        collada.types.ProfileCommon(
                            id=None,
                            newparam=[
                                collada.types.Newparam(
                                    sid='troll_cleric29_max2010_jpg-surface',
                                    parameter_type=collada.types.Surface(
                                        type=collada.types.FxSurfaceType._2D,
                                        init_from=collada.types.InitFrom(uri='troll_cleric29_max2010_jpg')
                                    )
                                ),
                                collada.types.Newparam(
                                    sid='troll_cleric29_max2010_jpg-sampler',
                                    parameter_type=collada.types.Sampler2D(
                                        source=collada.types.SourceFX(sid='troll_cleric29_max2010_jpg-surface')
                                    )
                                )
                            ],
                            technique=collada.types.TechniqueFX(
                                id=None,
                                sid='common',
                                shader=collada.types.Blinn(
                                    emission=collada.types.Color(value=(0.0, 0.0, 0.0, 1.0)),
                                    ambient=collada.types.Color(
                                        value=(0.8588236, 0.254902, 0.9137256, 1.0)
                                    ),
                                    diffuse=collada.types.Texture(
                                        texture='troll_cleric29_max2010_jpg-sampler',
                                        texcoord='CHANNEL1'
                                    ),
                                    specular=collada.types.Color(value=(0.0, 0.0, 0.0, 1.0)),
                                    shininess=collada.types.Float(value=10.0),
                                    reflective=collada.types.Color(value=(0.0, 0.0, 0.0, 1.0)),
                                    reflectivity=None,
                                    transparent=collada.types.Color(value=(1.0, 1.0, 1.0, 1.0)),
                                    transparency=collada.types.Float(value=1.0),
                                    index_of_refraction=None
                                )
                            )
                        )
                    ]
                )
            ]
        )
    ],
    library_materials=[
        collada.types.LibraryMaterials(
            id=None,
            name=None,
            materials=[
                collada.types.Material(
                    id='CubeMaterialTextured-material',
                    name='CubeMaterialTextured',
                    instance_effect=collada.types.InstanceEffect(
                        sid=None,
                        name=None,
                        url='#CubeMaterialTextured'
                    )
                )
            ]
        )
    ],
    library_geometries=[
        collada.types.LibraryGeometries(
            id=None,
            name=None,
            geometries=[
                collada.types.Geometry(
                    id='geom-Cube',
                    name='Cube',
                    geometric_element=collada.types.Mesh(
                        sources=[
                            collada.types.SourceCore(
                                id='geom-Cube-positions',
                                name=None,
                                array_element=collada.types.FloatArray(
                                    count=24,
                                    id='geom-Cube-positions-array',
                                    name=None,
                                    digits=6,
                                    magnitude=38,
                                    floats=[
                                        -0.5,
                                        -0.5,
                                        0.0,
                                        0.5,
                                        -0.5,
                                        0.0,
                                        -0.5,
                                        0.5,
                                        0.0,
                                        0.5,
                                        0.5,
                                        0.0,
                                        -0.5,
                                        -0.5,
                                        1.0,
                                        0.5,
                                        -0.5,
                                        1.0,
                                        -0.5,
                                        0.5,
                                        1.0,
                                        0.5,
                                        0.5,
                                        1.0
                                    ]
                                ),
                                technique_common=collada.types.TechniqueCommon_SourceCore(
                                    accessor=collada.types.Accessor(
                                        count=8,
                                        offset=0,
                                        source='#geom-Cube-positions-array',
                                        stride=3,
                                        params=[
                                            collada.types.Param(name='X', sid=None, type='float', semantic=None),
                                            collada.types.Param(name='Y', sid=None, type='float', semantic=None),
                                            collada.types.Param(name='Z', sid=None, type='float', semantic=None)
                                        ]
                                    )
                                )
                            ),
                            collada.types.SourceCore(
                                id='geom-Cube-normals',
                                name=None,
                                array_element=collada.types.FloatArray(
                                    count=72,
                                    id='geom-Cube-normals-array',
                                    name=None,
                                    digits=6,
                                    magnitude=38,
                                    floats=[
                                        0.0,
                                        0.0,
                                        -1.0,
                                        0.0,
                                        0.0,
                                        -1.0,
                                        0.0,
                                        0.0,
                                        -1.0,
                                        0.0,
                                        0.0,
                                        -1.0,
                                        0.0,
                                        0.0,
                                        1.0,
                                        0.0,
                                        0.0,
                                        1.0,
                                        0.0,
                                        0.0,
                                        1.0,
                                        0.0,
                                        0.0,
                                        1.0,
                                        0.0,
                                        -1.0,
                                        0.0,
                                        0.0,
                                        -1.0,
                                        0.0,
                                        0.0,
                                        -1.0,
                                        0.0,
                                        0.0,
                                        -1.0,
                                        0.0,
                                        1.0,
                                        0.0,
                                        0.0,
                                        1.0,
                                        0.0,
                                        0.0,
                                        1.0,
                                        0.0,
                                        0.0,
                                        1.0,
                                        0.0,
                                        0.0,
                                        0.0,
                                        1.0,
                                        0.0,
                                        0.0,
                                        1.0,
                                        0.0,
                                        0.0,
                                        1.0,
                                        0.0,
                                        0.0,
                                        1.0,
                                        0.0,
                                        -1.0,
                                        0.0,
                                        0.0,
                                        -1.0,
                                        0.0,
                                        0.0,
                                        -1.0,
                                        0.0,
                                        0.0,
                                        -1.0,
                                        0.0,
                                        0.0
                                    ]
                                ),
                                technique_common=collada.types.TechniqueCommon_SourceCore(
                                    accessor=collada.types.Accessor(
                                        count=24,
                                        offset=0,
                                        source='#geom-Cube-normals-array',
                                        stride=3,
                                        params=[
                                            collada.types.Param(name='X', sid=None, type='float', semantic=None),
                                            collada.types.Param(name='Y', sid=None, type='float', semantic=None),
                                            collada.types.Param(name='Z', sid=None, type='float', semantic=None)
                                        ]
                                    )
                                )
                            ),
                            collada.types.SourceCore(
                                id='geom-Cube-map1',
                                name=None,
                                array_element=collada.types.FloatArray(
                                    count=36,
                                    id='geom-Cube-map1-array',
                                    name=None,
                                    digits=6,
                                    magnitude=38,
                                    floats=[
                                        0.0,
                                        0.0,
                                        0.0,
                                        1.0,
                                        0.0,
                                        0.0,
                                        0.0,
                                        1.0,
                                        0.0,
                                        1.0,
                                        1.0,
                                        0.0,
                                        0.0,
                                        0.0,
                                        0.0,
                                        1.0,
                                        0.0,
                                        0.0,
                                        0.0,
                                        1.0,
                                        0.0,
                                        1.0,
                                        1.0,
                                        0.0,
                                        0.0,
                                        0.0,
                                        0.0,
                                        1.0,
                                        0.0,
                                        0.0,
                                        0.0,
                                        1.0,
                                        0.0,
                                        1.0,
                                        1.0,
                                        0.0
                                    ]
                                ),
                                technique_common=collada.types.TechniqueCommon_SourceCore(
                                    accessor=collada.types.Accessor(
                                        count=12,
                                        offset=0,
                                        source='#geom-Cube-map1-array',
                                        stride=3,
                                        params=[
                                            collada.types.Param(name='S', sid=None, type='float', semantic=None),
                                            collada.types.Param(name='T', sid=None, type='float', semantic=None),
                                            collada.types.Param(name='P', sid=None, type='float', semantic=None)
                                        ]
                                    )
                                )
                            )
                        ],
                        vertices=collada.types.Vertices(
                            id='geom-Cube-vertices',
                            name=None,
                            inputs=[
                                collada.types.InputUnshared(
                                    semantic='POSITION',
                                    source='#geom-Cube-positions'
                                )
                            ]
                        ),
                        primitive_elements=[
                            collada.types.Triangles(
                                name=None,
                                count=12,
                                material='CubeMaterialTextured',
                                inputs=[
                                    collada.types.InputShared(
                                        offset=0,
                                        semantic='VERTEX',
                                        source='#geom-Cube-vertices',
                                        set=None
                                    ),
                                    collada.types.InputShared(
                                        offset=1,
                                        semantic='NORMAL',
                                        source='#geom-Cube-normals',
                                        set=None
                                    ),
                                    collada.types.InputShared(
                                        offset=2,
                                        semantic='TEXCOORD',
                                        source='#geom-Cube-map1',
                                        set=0
                                    )
                                ],
                                p=[
                                    0,
                                    0,
                                    9,
                                    2,
                                    1,
                                    11,
                                    3,
                                    2,
                                    10,
                                    3,
                                    2,
                                    10,
                                    1,
                                    3,
                                    8,
                                    0,
                                    0,
                                    9,
                                    4,
                                    4,
                                    8,
                                    5,
                                    5,
                                    9,
                                    7,
                                    6,
                                    11,
                                    7,
                                    6,
                                    11,
                                    6,
                                    7,
                                    10,
                                    4,
                                    4,
                                    8,
                                    0,
                                    8,
                                    4,
                                    1,
                                    9,
                                    5,
                                    5,
                                    10,
                                    7,
                                    5,
                                    10,
                                    7,
                                    4,
                                    11,
                                    6,
                                    0,
                                    8,
                                    4,
                                    1,
                                    12,
                                    0,
                                    3,
                                    13,
                                    1,
                                    7,
                                    14,
                                    3,
                                    7,
                                    14,
                                    3,
                                    5,
                                    15,
                                    2,
                                    1,
                                    12,
                                    0,
                                    3,
                                    16,
                                    4,
                                    2,
                                    17,
                                    5,
                                    6,
                                    18,
                                    7,
                                    6,
                                    18,
                                    7,
                                    7,
                                    19,
                                    6,
                                    3,
                                    16,
                                    4,
                                    2,
                                    20,
                                    0,
                                    0,
                                    21,
                                    1,
                                    4,
                                    22,
                                    3,
                                    4,
                                    22,
                                    3,
                                    6,
                                    23,
                                    2,
                                    2,
                                    20,
                                    0
                                ]
                            )
                        ]
                    )
                )
            ]
        )
    ],
    library_lights=[
        collada.types.LibraryLights(
            id=None,
            name=None,
            lights=[
                collada.types.Light(
                    id='EnvironmentAmbientLight',
                    name='EnvironmentAmbientLight',
                    technique_common=collada.types.TechniqueCommon_Light(
                        light=collada.types.Ambient(color=(0.0, 0.0, 0.0))
                    )
                )
            ]
        )
    ],
    library_images=[
        collada.types.LibraryImages(
            id=None,
            name=None,
            images=[
                collada.types.Image(
                    id='troll_cleric29_max2010_jpg',
                    name=None,
                    format=None,
                    height=None,
                    width=None,
                    depth=None,
                    image_source=collada.types.InitFrom(
                        uri='file:///C:/cygwin/home/bilbo/collada/images/0_troll_cleric29_max2010.'
                            'jpg'
                    )
                )
            ]
        )
    ],
    library_visual_scenes=[
        collada.types.LibraryVisualScenes(
            id=None,
            name=None,
            visual_scenes=[
                collada.types.VisualScene(
                    id='MaxScene',
                    name=None,
                    nodes=[
                        collada.types.Node(
                            id=None,
                            name='EnvironmentAmbientLight',
                            sid=None,
                            type=collada.types.NodeType.NODE,
                            layer=[],
                            transformation_elements=[],
                            instance_geometries=[],
                            instance_lights=[
                                collada.types.InstanceLight(
                                    sid=None,
                                    name=None,
                                    url='#EnvironmentAmbientLight'
                                )
                            ],
                            nodes=[]
                        ),
                        collada.types.Node(
                            id='node-Cube',
                            name='Cube',
                            sid=None,
                            type=collada.types.NodeType.NODE,
                            layer=[],
                            transformation_elements=[],
                            instance_geometries=[],
                            instance_lights=[],
                            nodes=[
                                collada.types.Node(
                                    id=None,
                                    name=None,
                                    sid=None,
                                    type=collada.types.NodeType.NODE,
                                    layer=[],
                                    transformation_elements=[
                                        collada.types.Matrix(
                                            sid=None,
                                            values=(
                                                (1.0, 0.0, 0.0, 0.0),
                                                (0.0, 1.0, -4.37114e-08, 2.18557e-08),
                                                (0.0, 4.37114e-08, 1.0, -0.5),
                                                (0.0, 0.0, 0.0, 1.0)
                                            )
                                        )
                                    ],
                                    instance_geometries=[
                                        collada.types.InstanceGeometry(
                                            sid=None,
                                            name=None,
                                            url='#geom-Cube',
                                            bind_material=collada.types.BindMaterial(
                                                technique_common=collada.types.TechniqueCommon_BindMaterial(
                                                    materials=[
                                                        collada.types.InstanceMaterial(
                                                            sid=None,
                                                            name=None,
                                                            target='#CubeMaterialTextured-material',
                                                            symbol='CubeMaterialTextured',
                                                            bind_vertex_inputs=[
                                                                collada.types.BindVertexInput(
                                                                    semantic='CHANNEL1',
                                                                    input_semantic='TEXCOORD',
                                                                    input_set='0'
                                                                )
                                                            ]
                                                        )
                                                    ]
                                                )
                                            )
                                        )
                                    ],
                                    instance_lights=[],
                                    nodes=[]
                                )
                            ]
                        )
                    ]
                )
            ]
        )
    ],
    scenes=[
        collada.types.Scene(
            instance_visual_scene=collada.types.InstanceVisualScene(
                sid=None,
                name=None,
                url='#MaxScene'
            )
        )
    ]
)
